#!/usr/bin/env python3
#
# flex-sim — synthetic FlexRadio-6000 emulator / test bench for AetherSDR.
# Copyright (C) 2026 Nigel Fenton (G0JKN)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version. Distributed WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
# License for more details. You should have received a copy of the GNU GPL along
# with this program; if not, see <https://www.gnu.org/licenses/>.
#
# Code generated by Claude (Anthropic) via Claude Code, directed and tested by
# the copyright holder.
"""flex-sim — a synthetic FlexRadio-6000 emulator for testing AetherSDR.

flex-sim impersonates a FlexRadio 6000's data plane: it answers SmartSDR
discovery + the FlexLib control handshake, then streams synthetic VITA-49
panadapter / waterfall / meter data so AetherSDR renders a waterfall, S-meter and
TX meters from a programmable signal engine — a deterministic, hardware-free test
bench for AE's spectrum / waterfall / CW code. (Wire format reverse-engineered
from AE's own decoder; see PROTOCOL.md.)

It serves a live browser control panel (default http://<ip>:8731/) with a pattern
picker, dBm/S-unit level controls, TX keying and CW/CWX — each pattern shows what
it exercises in AE.

NETWORKING: by default flex-sim binds UDP :4992 like a real radio, so give it its
own IP (second machine / VM / container / WSL2) — OR use --port to run it on the SAME
host as AE on a different control port. Pass --ae <AE-ip> to also unicast discovery to AE.

Pure Python 3.8+ stdlib — no dependencies.

Usage:  python3 flex_sim.py [--ip IP] [--ae AE_IP] [--pattern NAME] [--port P]
                            [--bins N] [--fps N] [--width-khz K] [--ctl-port P]
  --port lets flex-sim run on the SAME host as AE: it binds/advertises that port
  (e.g. 5992) for control+data while still announcing to AE's fixed :4992 listener.
Patterns (each is a test signal; the control panel explains what to look for):
  noise_floor   flat floor (baseline; auto-black #3586)
  ramp          whole-span level swept min->max (auto-black / level mapping)
  cal_tones     fixed carriers at known dBm (verify the dB scale)
  carrier       steady tone on the VFO (S-meter / dBm calibration)
  cw            20-wpm Morse 'CQ CQ CQ TST' (sim-keyed)
  swept_carrier one tone sweeping the span (freq mapping / tile decode)
  comb          N evenly-spaced tones (dynamic range)
  step          whole-span square wave in time (temporal response)
  impulse       brief full-span flash each period (transient response)
  staircase     center carrier stepping floor->max (colormap ladder)
  noise         random noise band, white->pink tilt
  tx_blank      periodic real TX gap -> repro #2126 / #1916
Also handles AE's own CWX keyer (cwx send/wpm/qsk_enabled) for authentic CW TX.
"""
import argparse, http.server, json, math, random, socket, struct, threading, time, urllib.parse, uuid

FLEX_SIM_VERSION = "0.1.0"

DISCOVERY_PORT = 4992        # AE always listens for discovery here (fixed); we broadcast TO it
DEFAULT_PORT = 4992          # flex-sim's own control (TCP) + VITA-prime (UDP) port; override with --port
                             # -> set e.g. 5992 to run on the SAME host as AE without a :4992 clash
HANDLE = 0x1A2B3C4D
HANDLE_HEX = f"{HANDLE:08X}"
PAN_ID = 0x40000000          # FFT stream id   (PCC 0x8003)
WF_ID  = 0x42000000          # waterfall id    (PCC 0x8004)
SERIAL, MODEL, VERSION = "EMULATE01", "FLEX-6600", "3.3.28.0"

CENTER_MHZ, SPAN_MHZ, BINS, FPS = 14.100, 0.250, 1024, 20
PCC_FFT, PCC_WF, PCC_METER = 0x8003, 0x8004, 0x8002
METER_SID = 0x46000000       # meter VITA stream id (AE routes meters by PCC, not by sid)
SLC_LEVEL_ID = 1             # meter index for the slice S-meter (src=SLC nam=LEVEL unit=dBm)
FWDPWR_ID, SWR_ID = 2, 3     # TX meters: forward power (src=TX nam=FWDPWR, dBm->W) + SWR

# pattern timing/shape defaults (seconds / counts)
RAMP_PERIOD = 10.0
SWEEP_PERIOD = 8.0
STEP_DT = 1.0
IMPULSE_PERIOD, IMPULSE_WIDTH = 2.0, 0.15
COMB_TONES = 8
TXBLANK_PERIOD, TXBLANK_GAP = 6.0, 2.0
STAIRCASE_STEPS, STAIRCASE_DWELL = 10, 0.6        # 0->max amplitude ladder
SIGNAL_WIDTH_KHZ = 10.0                            # synthesized carrier/signal width (kHz)
CW_TEXT, CW_WPM, CW_TAIL_GAP = "CQ CQ CQ TST CQ CQ CQ TST", 20, 2.0   # CW keyer (Morse) pattern
CWX_TAIL_S = 0.6            # hold TX this long after the last CWX element so AE's keyer drains first
WF_FLOOR_VAL, WF_PEAK_VAL = 70.0, 235.0   # AE int16/128 intensity for our [min_dbm,max_dbm] range:
                                          # low dBm -> ~black, high dBm -> bright. (Waterfall colour
                                          # still depends on AE's black_level/color_gain; panadapter
                                          # + S-meter read the exact dBm regardless.)
S9_DBM = -73.0                            # HF S-meter convention: S9 = -73 dBm, 6 dB per S-unit


def log(*a):
    print(time.strftime("%H:%M:%S"), *a, flush=True)


def local_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80)); return s.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        s.close()


def parse_kvs(text):
    return dict(tok.split("=", 1) for tok in text.split() if "=" in tok)


# ---- VITA-49 builders (PROTOCOL.md §5, big-endian, 28-byte header) ----
def vita_header(stream_id, pcc, seq, payload_len):
    total_words = (28 + payload_len + 3) // 4
    word0 = (0x3 << 28) | (1 << 27) | ((seq & 0xF) << 16) | (total_words & 0xFFFF)
    return struct.pack(">IIIIIII", word0, stream_id, 0x001C2D00, pcc & 0xFFFF, 0, 0, 0)


def fft_packet(stream_id, seq, pixels, frame_index):
    n = len(pixels)
    sub = struct.pack(">HHHHI", 0, n, 2, n, frame_index)
    payload = sub + struct.pack(">%dH" % n, *pixels)
    return vita_header(stream_id, PCC_FFT, seq, len(payload)) + payload


def wf_packet(stream_id, seq, intens, low_hz, binbw_hz, timecode, auto_black=20):
    # auto_black = the tile's AutoBlackLevel field (raw uint, same domain as the
    # intensity samples). A real Flex puts the radio-measured noise-floor level
    # here; AE's #3586 auto-black path uses it as the waterfall black/low point.
    # Pass the frame's measured floor (min raw) for faithful emulation.
    w = len(intens)
    low_raw = int(round(low_hz))                           # plain Hz (|val|<1e11 -> AE decodes as Hz;
    binbw_raw = int(round(binbw_hz))                       # unambiguous for HF/VHF, unlike Hz*2^20 at low f)
    sub = struct.pack(">qqIHHIIHH", low_raw, binbw_raw, 100, w, 1, timecode, auto_black, w, 0)
    payload = sub + struct.pack(">%dh" % w, *intens)       # signed int16, AE reads /128.0
    return vita_header(stream_id, PCC_WF, seq, len(payload)) + payload


def meter_packet(stream_id, seq, meter_id, dbm):
    # PCC 0x8002 payload: N x (uint16 meter_id, int16 raw). AE: dBm = raw / 128.0
    raw = max(-32768, min(32767, int(round(dbm * 128.0))))
    payload = struct.pack(">Hh", meter_id, raw)
    return vita_header(stream_id, PCC_METER, seq, len(payload)) + payload


# ---- pattern engine: each pattern returns a per-bin dBm list (or None = TX gap) ----
class PatternCtx:
    def __init__(self, n, center_bin, min_dbm, max_dbm):
        self.n, self.center = n, center_bin
        self.min_dbm, self.max_dbm = min_dbm, max_dbm
        self.floor = min_dbm + 10.0           # visible noise floor (live: noise-floor slider)
        self.sig_level = max_dbm - 5.0        # signal peak level (live: signal-level slider)
        self.sig_half = 2                     # half-width of a synthesized signal, in bins
        self.noise_color = 0.0                # noise tilt dB across band (0=white, >0=pink)
        self.cw_keydown = False               # CW keyer: element key-down this frame
        self.cw_in_message = False            # CW keyer: inside the message (TX over), not the tail gap
        self.cw_qsk = False                   # CW/CWX: full break-in (RX peeks between elements)


def _flat(ctx, dbm):
    return [dbm] * ctx.n


def pat_noise_floor(ctx, t):
    return _flat(ctx, ctx.floor)


def pat_ramp(ctx, t):
    frac = (t % RAMP_PERIOD) / RAMP_PERIOD
    return _flat(ctx, ctx.min_dbm + frac * (ctx.max_dbm - ctx.min_dbm))


def pat_cal_tones(ctx, t):
    out = _flat(ctx, ctx.floor)
    for frac, dbm in [(0.2, -100), (0.4, -80), (0.6, -60), (0.8, -40)]:
        b = int(frac * ctx.n)
        for d in (-1, 0, 1):
            if 0 <= b + d < ctx.n:
                out[b + d] = max(out[b + d], dbm)
    return out


def pat_swept_carrier(ctx, t):
    out = _flat(ctx, ctx.floor)
    c = int(((t % SWEEP_PERIOD) / SWEEP_PERIOD) * (ctx.n - 1))
    for d in range(-ctx.sig_half, ctx.sig_half + 1):
        b = c + d
        if 0 <= b < ctx.n:
            out[b] = ctx.sig_level
    return out


def pat_comb(ctx, t):
    out = _flat(ctx, ctx.floor)
    step = max(1, ctx.n // COMB_TONES)
    for b in range(step // 2, ctx.n, step):
        out[b] = ctx.sig_level - 10
    return out


def pat_step(ctx, t):
    hi = int(t / STEP_DT) % 2 == 0
    return _flat(ctx, ctx.sig_level if hi else ctx.floor)


def pat_impulse(ctx, t):
    bright = (t % IMPULSE_PERIOD) < IMPULSE_WIDTH
    return _flat(ctx, ctx.sig_level if bright else ctx.floor)


def pat_noise(ctx, t):
    # A band of random noise, `sig_width_khz` wide, centered at the VFO. noise_color
    # tilts the band: 0 = white (flat), higher = pink/red (more power on the low side).
    out = [ctx.floor] * ctx.n
    lo = max(0, ctx.center - ctx.sig_half)
    hi = min(ctx.n - 1, ctx.center + ctx.sig_half)
    span = max(1, hi - lo)
    for b in range(lo, hi + 1):
        frac = (b - lo) / span                            # 0 low edge -> 1 high edge
        env = ctx.sig_level - ctx.noise_color * frac      # spectral tilt
        out[b] = env - random.uniform(0.0, 12.0)          # per-bin random texture
    return out


def pat_tx_blank(ctx, t):
    # Periodic TX gap. During the gap return None (no pan/wf data); stream_loop
    # ALSO asserts real TX state (interlock TRANSMITTING + forward power) so AE
    # runs its waterfall-during-TX path -> repro #2126 (blank/flicker during TX)
    # and #1916 (waterfall gone after TX).
    if (t % TXBLANK_PERIOD) < TXBLANK_GAP:
        return None                                    # TX gap: send nothing
    out = _flat(ctx, ctx.floor)
    for d in range(-ctx.sig_half, ctx.sig_half + 1):   # honour the width slider, like carrier/staircase
        b = ctx.center + d
        if 0 <= b < ctx.n:
            out[b] = ctx.sig_level
    return out


def pat_staircase(ctx, t):
    # A center carrier whose amplitude steps floor->max in STAIRCASE_STEPS discrete
    # levels (each held STAIRCASE_DWELL s), then repeats. Watch the waterfall carrier
    # climb out of black in even brightness steps -> shows the colormap/black threshold.
    cycle = STAIRCASE_STEPS * STAIRCASE_DWELL
    step = int((t % cycle) / STAIRCASE_DWELL)              # 0 .. STEPS-1
    frac = step / max(1, STAIRCASE_STEPS - 1)
    level = ctx.floor + frac * (ctx.sig_level - ctx.floor)   # floor (0) -> signal level
    out = [ctx.floor] * ctx.n
    for d in range(-ctx.sig_half, ctx.sig_half + 1):
        b = ctx.center + d
        if 0 <= b < ctx.n:
            out[b] = level
    return out


def pat_carrier(ctx, t):
    # Steady carrier at the VFO at sig_level — for S-meter / dBm calibration.
    out = [ctx.floor] * ctx.n
    for d in range(-ctx.sig_half, ctx.sig_half + 1):
        b = ctx.center + d
        if 0 <= b < ctx.n:
            out[b] = ctx.sig_level
    return out


# ---- CW keyer (Morse) ----
_MORSE = {
    "A": ".-", "B": "-...", "C": "-.-.", "D": "-..", "E": ".", "F": "..-.",
    "G": "--.", "H": "....", "I": "..", "J": ".---", "K": "-.-", "L": ".-..",
    "M": "--", "N": "-.", "O": "---", "P": ".--.", "Q": "--.-", "R": ".-.",
    "S": "...", "T": "-", "U": "..-", "V": "...-", "W": ".--", "X": "-..-",
    "Y": "-.--", "Z": "--..", "0": "-----", "1": ".----", "2": "..---",
    "3": "...--", "4": "....-", "5": ".....", "6": "-....", "7": "--...",
    "8": "---..", "9": "----.", "/": "-..-.", "?": "..--..", ".": ".-.-.-",
    ",": "--..--", "=": "-...-",
}


def _schedule_keydown(schedule, tt):
    acc = 0.0
    for on, dur in schedule:
        if tt < acc + dur:
            return on
        acc += dur
    return False


def _morse_schedule(text, wpm):
    # [(key_down, seconds), ...] for `text` at `wpm` (PARIS timing: dit = 1.2/wpm s).
    dit = 1.2 / wpm
    seg = []
    for wi, word in enumerate(text.split(" ")):
        if wi:
            seg.append((False, 7 * dit))                # inter-word gap
        for ci, ch in enumerate(word):
            code = _MORSE.get(ch.upper())
            if not code:
                continue
            if ci:
                seg.append((False, 3 * dit))            # inter-character gap
            for ei, el in enumerate(code):
                if ei:
                    seg.append((False, dit))            # intra-character gap
                seg.append((True, (3 if el == "-" else 1) * dit))
    return seg


def _morse_char_ends(text, wpm):
    # Cumulative time (s) at which each keyed character finishes — for 'cwx sent=N'.
    dit = 1.2 / wpm
    t, ends = 0.0, []
    for wi, word in enumerate(text.split(" ")):
        if wi:
            t += 7 * dit
        for ci, ch in enumerate(word):
            code = _MORSE.get(ch.upper())
            if not code:
                continue
            if ci:
                t += 3 * dit
            for ei, el in enumerate(code):
                if ei:
                    t += dit
                t += (3 if el == "-" else 1) * dit
            ends.append(t)
    return ends


CW_SCHEDULE = _morse_schedule(CW_TEXT, CW_WPM) + [(False, CW_TAIL_GAP)]
CW_CYCLE = sum(d for _, d in CW_SCHEDULE)


def pat_cw(ctx, t):
    # Sim-driven Morse keyer at CW_WPM (the panel "Send CW" button — the sim fakes
    # the keying). key-down = TX burst (RX muted -> None); key-up = brief RX (carrier);
    # tail gap = RX; repeat. (For an AE-initiated over, use CWX — see handle_cwx.)
    tt = t % CW_CYCLE
    keydown = _schedule_keydown(CW_SCHEDULE, tt)
    in_msg = tt < (CW_CYCLE - CW_TAIL_GAP)
    ctx.cw_keydown = keydown
    ctx.cw_in_message = in_msg
    if keydown or (in_msg and not ctx.cw_qsk):          # TX burst, or non-QSK over: RX muted
        return None
    out = [ctx.floor] * ctx.n                            # QSK key-up peek, or the tail RX gap
    for d in range(-ctx.sig_half, ctx.sig_half + 1):
        b = ctx.center + d
        if 0 <= b < ctx.n:
            out[b] = ctx.sig_level
    return out


PATTERNS = {
    "carrier": pat_carrier, "cw": pat_cw,
    "noise_floor": pat_noise_floor, "ramp": pat_ramp, "cal_tones": pat_cal_tones,
    "swept_carrier": pat_swept_carrier, "comb": pat_comb, "step": pat_step,
    "impulse": pat_impulse, "tx_blank": pat_tx_blank, "staircase": pat_staircase,
    "noise": pat_noise,
}
AUTO_TX_PATTERNS = {"tx_blank", "cw"}     # patterns that drive TX state themselves


class Radio:
    def __init__(self, ip, ae_ip, pattern="ramp", bins=BINS, fps=FPS, width_khz=SIGNAL_WIDTH_KHZ,
                 port=DEFAULT_PORT, radio_id=0):
        self.ip, self.ae_ip = ip, ae_ip
        self.port = port                # control/data port we bind + advertise (discovery dest stays 4992)
        # Per-radio identity, so many radios can live in one process (the "rack").
        # Each value must be unique per radio or AE cross-wires them; derived from
        # radio_id off the base constants below.
        self.radio_id = radio_id
        self.serial = f"FLEXSIM{radio_id:02d}"
        self.client_handle = HANDLE + radio_id   # NB: NOT self.handle — that's the method!
        self.handle_hex = f"{self.client_handle:08X}"
        self.pan_id = PAN_ID + radio_id          # FFT stream id (PCC 0x8003)
        self.wf_id = WF_ID + radio_id            # waterfall stream id (PCC 0x8004)
        self.meter_sid = METER_SID + radio_id    # meter VITA stream id (PCC 0x8002)
        self.pattern = pattern if pattern in PATTERNS else "ramp"
        self.bins, self.fps = bins, fps
        self.sig_width_khz = width_khz
        self.noise_floor_dbm = -120.0   # live (control panel, dBm; ~S1)
        self.sig_level_dbm = S9_DBM     # live (control panel, dBm; default S9 = -73)
        self.noise_color = 0.0          # live (noise tilt: 0=white, >0=pink)
        self.vita_dest = None
        self.run = True
        self.send_lock = threading.Lock()   # serialize TCP writes: stream thread (status) vs command thread (replies)
        self.streaming = False
        self.ae_peer_ip = None          # only accept the UDP prime from the connected AE
        self.y_pixels, self.min_dbm, self.max_dbm = 700, -130.0, -20.0
        self.center_mhz, self.span_mhz = CENTER_MHZ, SPAN_MHZ   # track AE's actual pan view
        self.slice_freq = CENTER_MHZ                            # follows AE's slice-create freq (= VFO)
        self.slice_mode = "USB"
        self.conn = None            # active TCP conn (so the control panel can push TX status)
        self.tx_mox = False         # live: TX keyed (panel toggle or AE's 'transmit set mox=1')
        self.tx_tune = False
        self.tx_power_w = 100.0      # live: forward power (W) reported while TX
        self.tx_swr = 1.2           # live: SWR reported while TX
        self.cwx_wpm = 20           # CWX keyer speed (AE drives via 'cwx wpm')
        self.cwx_active = False      # an AE-initiated CWX transmission is in progress
        self.cwx_schedule = []
        self.cwx_dur = 0.0
        self.cwx_t0 = 0.0
        self.cwx_char_ends = []
        self.cwx_sent = 0
        self.qsk = False             # full break-in (RX between elements); AE sets via cwx qsk_enabled
        self.enabled = True          # "power": when False, stop advertising (radio drops off AE)
        self.last_vfo_dbm = -130.0   # last level at the VFO — drives the rack strip's signal meter

    @property
    def tx_on(self):
        return self.tx_mox or self.tx_tune

    def set_power(self, on):
        # Rack "power button": off -> stop streaming + drop AE's connection + stop
        # advertising (radio vanishes from AE). on -> discovery resumes, AE re-finds it.
        self.enabled = bool(on)
        if not on:
            self.streaming = False
            c = self.conn
            if c:
                try: c.shutdown(socket.SHUT_RDWR); c.close()
                except OSError: pass

    def state(self):
        # Snapshot for the rack strip (polled by the panel).
        return {"id": self.radio_id, "serial": self.serial, "on": self.enabled,
                "connected": self.conn is not None, "freq": round(self.slice_freq, 5),
                "mode": self.slice_mode, "tx": self.tx_on, "pattern": self.pattern,
                "power_w": round(self.tx_power_w), "meter_dbm": round(self.last_vfo_dbm, 1)}

    def dbm_to_pixel(self, dbm):
        p = (self.max_dbm - dbm) / (self.max_dbm - self.min_dbm) * (self.y_pixels - 1)
        return max(0, min(self.y_pixels - 1, int(round(p))))

    def dbm_to_wf_raw(self, dbm):
        frac = max(0.0, min(1.0, (dbm - self.min_dbm) / (self.max_dbm - self.min_dbm)))
        return int(round((WF_FLOOR_VAL + frac * (WF_PEAK_VAL - WF_FLOOR_VAL)) * 128))

    def discovery_loop(self):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        msg = (f"name=flex-sim model={MODEL} serial={self.serial} version={VERSION} "
               f"ip={self.ip} port={self.port} status=Available mf_enable=1 "
               f"max_licensed_version=3").encode()
        dests = [("255.255.255.255", DISCOVERY_PORT)] + ([(self.ae_ip, DISCOVERY_PORT)] if self.ae_ip else [])
        while self.run:
            if self.enabled:                       # "powered off" -> stop advertising
                for d in dests:
                    try: s.sendto(msg, d)
                    except OSError: pass
            time.sleep(1.0)

    def prime_loop(self):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind(("", self.port))
        while self.run:
            try:
                data, addr = s.recvfrom(2048)
            except OSError:
                break
            if self.ae_peer_ip and addr[0] == self.ae_peer_ip and not self.vita_dest:
                self.vita_dest = addr
                log(f"[udp] captured VITA dest from prime: {addr} ({len(data)}B)")

    def serve(self):
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind(("", self.port)); srv.listen(1)
        log(f"[tcp] listening on :{self.port}  (radio ip {self.ip}, pattern={self.pattern})")
        while self.run:
            conn, addr = srv.accept()
            log(f"[tcp] AE connected from {addr}")
            self.ae_peer_ip = addr[0]; self.vita_dest = None
            try: self.handle(conn)
            except Exception as e: log("[tcp] conn error:", e)
            finally: conn.close(); self.streaming = False; self.ae_peer_ip = None; self.conn = None

    def handle(self, conn):
        self.conn = conn
        with self.send_lock:
            conn.sendall(f"V{VERSION}\n".encode())
            conn.sendall(f"H{self.handle_hex}\n".encode())
        log(f"[tcp] sent V{VERSION} / H{self.handle_hex}")
        buf = b""
        while self.run:
            chunk = conn.recv(4096)
            if not chunk: break
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                line = line.decode(errors="replace").strip()
                if line: self.on_line(conn, line)

    def reply(self, conn, seq, body=""):
        with self.send_lock:
            conn.sendall(f"R{seq}|0|{body}\n".encode())

    def status(self, conn, obj_kvs):
        with self.send_lock:
            conn.sendall(f"S{self.handle_hex}|{obj_kvs}\n".encode())

    def on_line(self, conn, line):
        if not line.startswith("C") or "|" not in line:
            log("[<-] (non-C)", line); return
        head, cmd = line.split("|", 1)
        seq, c = head[1:], cmd.strip()
        log("[<-]", f"C{seq}|{c}")
        if c.startswith("client gui"):
            self.reply(conn, seq, str(uuid.uuid4()).upper())
        elif c == "slice list":
            self.reply(conn, seq, "")
        elif c.startswith("display panafall create") or c.startswith("display pan create"):
            self.reply(conn, seq, f"0x{self.pan_id:08X},0x{self.wf_id:08X}")
            self.emit_pan_status(conn)
        elif c.startswith("slice create"):
            kvs = parse_kvs(c)
            if "freq" in kvs:                              # follow AE's freq -> drives VFO + pan center
                self.slice_freq = float(kvs["freq"])
                self.center_mhz = self.slice_freq
            if "mode" in kvs:
                self.slice_mode = kvs["mode"]
            self.reply(conn, seq, "0")
            self.emit_slice_status(conn)
            self.emit_meter_status(conn)                   # define the slice S-meter (SLC/LEVEL)
            self.emit_pan_status(conn)                     # re-center pan + waterfall on the slice
        elif c.startswith("display pan set"):
            kvs = parse_kvs(c)
            if "ypixels" in kvs: self.y_pixels = max(2, int(kvs["ypixels"]))
            if "y_pixels" in kvs: self.y_pixels = max(2, int(kvs["y_pixels"]))
            if "min_dbm" in kvs: self.min_dbm = float(kvs["min_dbm"])
            if "max_dbm" in kvs: self.max_dbm = float(kvs["max_dbm"])
            if "center" in kvs: self.center_mhz = float(kvs["center"])      # align waterfall to AE's view
            if "bandwidth" in kvs: self.span_mhz = float(kvs["bandwidth"])
            self.reply(conn, seq)
        elif c.startswith("info"):
            self.reply(conn, seq, f"model={MODEL},chassis_serial={self.serial},callsign=SDRSIM,"
                                  f"name=flex-sim,software_ver={VERSION},ip={self.ip}")
        elif c == "mic list":
            self.reply(conn, seq, "MIC,LINE")
        elif c.startswith("client udpport"):
            try: log("[tcp] AE udpport =", int(c.split()[-1]))
            except ValueError: pass
            self.reply(conn, seq)
        elif c.startswith("stream create"):
            self.reply(conn, seq, "0x48000000")
        elif c.startswith("transmit set"):                 # AE keys TX (MOX / TUNE)
            kvs = parse_kvs(c)
            if "mox" in kvs:  self.tx_mox = kvs["mox"] == "1"
            if "tune" in kvs: self.tx_tune = kvs["tune"] == "1"
            self.reply(conn, seq)
            self.emit_transmit_status()
        elif c.startswith("cwx "):                          # AE's CW text keyer
            self.handle_cwx(c)
            self.reply(conn, seq)
        elif c.startswith("slice set") or c.startswith("slice tune"):
            kvs = parse_kvs(c)
            if "mode" in kvs: self.slice_mode = kvs["mode"]
            for k in ("RF_frequency", "freq"):
                if k in kvs:
                    self.slice_freq = float(kvs[k]); self.center_mhz = self.slice_freq
            self.reply(conn, seq)
            self.emit_slice_status(conn)
        else:
            self.reply(conn, seq)

    def emit_pan_status(self, conn):
        self.status(conn,
            f"display pan 0x{self.pan_id:08X} client_handle=0x{self.handle_hex} waterfall=0x{self.wf_id:08X} "
            f"center={self.center_mhz:.6f} bandwidth={self.span_mhz:.6f} min_dbm={self.min_dbm:.0f} "
            f"max_dbm={self.max_dbm:.0f} x_pixels={self.bins} y_pixels={self.y_pixels} fps={self.fps} "
            f"ant_list=ANT1 rxant=ANT1")
        self.status(conn,
            f"display waterfall 0x{self.wf_id:08X} client_handle=0x{self.handle_hex} panadapter=0x{self.pan_id:08X} "
            f"line_duration=100 center={self.center_mhz:.6f} bandwidth={self.span_mhz:.6f} "
            f"auto_black=1 black_level=15 color_gain=50")
        log("[->] emitted display pan + waterfall status")
        if not self.streaming:
            self.streaming = True
            threading.Thread(target=self.stream_loop, daemon=True).start()

    def emit_slice_status(self, conn):
        self.status(conn, f"slice 0 client_handle=0x{self.handle_hex} pan=0x{self.pan_id:08X} "
                          f"RF_frequency={self.slice_freq:.6f} mode={self.slice_mode} in_use=1 active=1")

    def emit_meter_status(self, conn):
        # Define the radio's meters. NB: meter status is '#'-separated
        # index.key=value tokens after "meter " (NOT space-separated, and NO
        # leading "meter N") -- RadioModel::handleMeterStatus.
        defs = [
            (SLC_LEVEL_ID, "SLC", "LEVEL",  "dBm", -150.0, 20.0),   # RX S-meter
            (FWDPWR_ID,    "TX",  "FWDPWR", "dBm",    0.0, 60.0),   # TX fwd power (dBm -> W)
            (SWR_ID,       "TX",  "SWR",    "SWR",    1.0, 10.0),   # TX SWR
        ]
        for i, src, nam, unit, lo, hi in defs:
            toks = "#".join([f"{i}.src={src}", f"{i}.num=0", f"{i}.nam={nam}",
                             f"{i}.unit={unit}", f"{i}.low={lo}", f"{i}.hi={hi}"])
            self.status(conn, f"meter {toks}")
        log("[->] emitted meter defs: SLC/LEVEL (S-meter) + TX/FWDPWR + TX/SWR")

    def emit_transmit_status(self):
        # interlock state drives AE's m_radioTransmitting; transmit status drives
        # the MOX/TUNE UI. tx_client_handle = our handle => AE sees us as TX owner.
        if not self.conn:
            return
        on = self.tx_on
        try:
            self.status(self.conn,
                f"interlock state={'TRANSMITTING' if on else 'READY'} source=SW "
                f"tx_client_handle=0x{self.handle_hex}")
            self.status(self.conn,
                f"transmit mox={1 if self.tx_mox else 0} tune={1 if self.tx_tune else 0} "
                f"freq={self.slice_freq:.6f} rfpower={int(self.tx_power_w)} "
                f"tunepower={int(self.tx_power_w)}")
            log(f"[->] TX {'ON' if on else 'off'}  ({self.tx_power_w:.0f} W, SWR {self.tx_swr:.1f})")
        except OSError:
            pass

    def emit_cwx_status(self, **kv):
        if not self.conn:
            return
        body = " ".join(f"{k}={v}" for k, v in kv.items())
        try:
            self.status(self.conn, f"cwx {body}")
        except OSError:
            pass

    def handle_cwx(self, c):
        rest = c[4:].strip()                               # after "cwx "
        if rest.startswith("wpm"):
            try: self.cwx_wpm = max(5, int(rest.split()[1]))
            except (IndexError, ValueError): pass
        elif rest.startswith("qsk"):                        # cwx qsk_enabled 0/1
            self.qsk = rest.split()[-1] == "1"
            log(f"[cwx] QSK {'on (full break-in)' if self.qsk else 'off (normal)'}")
        elif rest.startswith("send"):                      # cwx send "<enc>" <block>
            q1 = c.find('"'); q2 = c.find('"', q1 + 1)
            if q1 >= 0 and q2 > q1:
                text = c[q1 + 1:q2].replace("\x7f", " ")   # 0x7f = AE-encoded space
                self.start_cwx(text)
        elif rest.startswith("clear") or rest.startswith("erase"):
            if self.cwx_active:
                self.cwx_active = False
                if self.tx_mox:
                    self.tx_mox = False
                    self.emit_transmit_status()
                self.emit_cwx_status(queue=0)

    def start_cwx(self, text):
        sched = _morse_schedule(text, self.cwx_wpm)
        if not sched:
            return
        self.cwx_schedule = sched
        self.cwx_char_ends = _morse_char_ends(text, self.cwx_wpm)
        self.cwx_sent = 0
        self.cwx_dur = sum(d for _, d in sched) + CWX_TAIL_S   # tail so AE's local keyer finishes before unkey
        self.cwx_t0 = time.time()
        self.cwx_active = True
        log(f"[cwx] AE sent {text!r} @ {self.cwx_wpm} wpm  ({self.cwx_dur:.1f}s)")

    def _cwx_frame(self, ctx, now):
        # One frame of an AE-initiated CWX transmission. Returns (levels, keyed).
        el = now - self.cwx_t0
        if el >= self.cwx_dur:                             # buffer drained
            self.cwx_active = False
            if self.tx_mox:
                self.tx_mox = False
                self.emit_transmit_status()
            self.emit_cwx_status(queue=0)                  # -> AE releases MOX (#2450)
            log("[cwx] complete")
            return [ctx.floor] * ctx.n, False
        if not self.tx_mox:                                # key the over on the first frame
            self.tx_mox = True
            self.emit_transmit_status()
        keydown = _schedule_keydown(self.cwx_schedule, el)
        ctx.cw_keydown = keydown
        if keydown or not self.qsk:                        # TX burst, or non-QSK over: RX muted
            return None, keydown
        out = [ctx.floor] * ctx.n                           # QSK: RX peeks between elements
        for d in range(-ctx.sig_half, ctx.sig_half + 1):
            b = ctx.center + d
            if 0 <= b < ctx.n:
                out[b] = ctx.sig_level
        return out, keydown

    def stream_loop(self):
        t0 = time.time()
        while self.run and not self.vita_dest and time.time() - t0 < 12:
            time.sleep(0.1)
        if not self.vita_dest:
            log("[stream] no UDP prime in 12s — AE never opened the data path; cannot stream")
            return
        dest = self.vita_dest
        log(f"[stream] streaming '{self.pattern}' to {dest} @ {self.fps} fps (Ctrl-C to stop)")
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        ctx = PatternCtx(self.bins, self.bins // 2, self.min_dbm, self.max_dbm)
        gen = PATTERNS[self.pattern]
        fseq = wseq = mseq = fi = 0
        last_tc = -1                                                # throttle pan/wf to one per row
        start = time.time()
        while self.run and self.streaming:
            now = time.time()
            cw_mode = self.cwx_active or self.pattern == "cw"
            period = (1.0 / 50.0) if cw_mode else (1.0 / self.fps)  # 20-ms keying res for 20-wpm CW (60-ms dits)
            tc = int((now - start) * self.fps)                     # waterfall row index (loop-rate independent);
            #                                                        wall-clock so it JUMPS across a TX gap
            #                                                        (real-radio behaviour -> AE history reproj).
            ctx.min_dbm, ctx.max_dbm = self.min_dbm, self.max_dbm   # track AE's display-pan-set
            ctx.floor = self.noise_floor_dbm                        # live (control panel, dBm)
            ctx.sig_level = self.sig_level_dbm
            ctx.noise_color = self.noise_color
            ctx.cw_qsk = self.qsk
            binbw_hz = (self.span_mhz * 1e6) / self.bins            # track AE's live span
            ctx.sig_half = max(1, int(round((self.sig_width_khz * 1000.0) / binbw_hz / 2)))
            if self.cwx_active:                                    # AE-initiated CWX overrides the pattern
                levels, keyed = self._cwx_frame(ctx, now)
            else:
                gen = PATTERNS.get(self.pattern, gen)              # live pattern switch
                levels = gen(ctx, now - start)
                if self.pattern == "tx_blank":                    # faithful TX cycle: the gap == keyed.
                    want_tx = (levels is None)
                elif self.pattern == "cw":                        # Morse keyer: TX for the whole over
                    want_tx = ctx.cw_in_message
                else:
                    want_tx = None
                if want_tx is not None and want_tx != self.tx_mox:  # assert real TX -> repro #2126/#1916
                    self.tx_mox = want_tx
                    self.emit_transmit_status()
                keyed = ctx.cw_keydown if self.pattern == "cw" else self.tx_on
            if levels is not None and tc != last_tc:               # one pan/wf row per waterfall tick
                pixels = [self.dbm_to_pixel(d) for d in levels]     # (loop may run at 50 fps for CW keying;
                intens = [self.dbm_to_wf_raw(d) for d in levels]    #  don't flood AE with 50 fps of big FFT/wf)
                low_hz = (self.center_mhz - self.span_mhz / 2) * 1e6   # track AE's live view
                vfo_dbm = levels[ctx.center]                            # S-meter = level at the VFO
                self.last_vfo_dbm = vfo_dbm                             # feed the rack strip's meter
                wf_ab = min(intens)                                     # measured noise-floor black level (raw)
                #                                                        -> AE #3586 radio-auto-black path
                try:
                    s.sendto(fft_packet(self.pan_id, fseq & 0xF, pixels, fi), dest); fseq += 1
                    s.sendto(wf_packet(self.wf_id, wseq & 0xF, intens, low_hz, binbw_hz, tc, auto_black=wf_ab), dest); wseq += 1
                    s.sendto(meter_packet(self.meter_sid, mseq & 0xF, SLC_LEVEL_ID, vfo_dbm), dest); mseq += 1
                except OSError as e:
                    log("[stream] send error:", e); break
                fi += 1
                last_tc = tc
            # TX meters every frame: real power/SWR while keyed, ~0 W / 1.0 SWR when not,
            # so AE's meter decays back to zero on de-key. CW/CWX key power per element.
            pw = self.tx_power_w if keyed else 0.0
            sw = self.tx_swr if keyed else 1.0
            fwd_dbm = 10.0 * math.log10(max(pw, 1e-6)) + 30.0
            try:
                s.sendto(meter_packet(self.meter_sid, mseq & 0xF, FWDPWR_ID, fwd_dbm), dest); mseq += 1
                s.sendto(meter_packet(self.meter_sid, mseq & 0xF, SWR_ID, sw), dest); mseq += 1
            except OSError:
                pass
            dt = period - (time.time() - now)
            if dt > 0: time.sleep(dt)
        log("[stream] stopped")


# ---- live control panel (web UI served by the sim; drive from the host browser) ----
CONTROL_HTML = """<!DOCTYPE html><html><head><meta charset=utf-8><title>flex-sim control</title>
<style>body{{font-family:sans-serif;background:#111;color:#ddd;padding:18px;max-width:440px}}
h2{{color:#5cf}} label{{display:block;margin:16px 0 4px}} select,input[type=range]{{width:380px}}
.v{{color:#5cf;font-weight:bold}}</style></head><body>
<h2>flex-sim &mdash; live control</h2>
<label>Pattern</label><select id=pat onchange=upd()>{options}</select>
<div id=hint style="background:#15202b;border-left:3px solid #5cf;padding:8px 11px;margin:8px 0;font-size:13px;color:#bcd;line-height:1.45"></div>
<label>Noise floor: <span class=v id=floorv>-120</span> dBm <span class=v id=floors>(S1)</span></label>
<input type=range id=floor min=-130 max=-20 step=1 value=-120 oninput=upd()>
<label>Signal level: <span class=v id=levelv>-73</span> dBm <span class=v id=levels>(S9)</span></label>
<input type=range id=level min=-130 max=-10 step=1 value=-73 oninput=upd()>
<label>Signal width: <span class=v id=widthv>10</span> kHz</label>
<input type=range id=width min=1 max=250 step=1 value=10 oninput=upd()>
<label>Noise color (white&rarr;pink): <span class=v id=tiltv>0</span> dB tilt</label>
<input type=range id=tilt min=0 max=30 step=1 value=0 oninput=upd()>
<hr style="border-color:#333;margin:20px 0">
<label><input type=checkbox id=tx onchange=upd()> <b>TX (key) &mdash; forward-power meter</b></label>
<label>TX power: <span class=v id=txpwv>100</span> W</label>
<input type=range id=txpw min=0 max=100 step=1 value=100 oninput=upd()>
<label>SWR: <span class=v id=swrv>1.2</span> : 1</label>
<input type=range id=swr min=10 max=50 step=1 value=12 oninput=upd()>
<div style="margin-top:14px">
<button onclick="sendcw(0)">&#9654; CW normal</button>
<button onclick="sendcw(1)">&#9654; CW full break-in</button>
<button onclick="setp('carrier')">&#9632; Stop</button>
</div>
<div style="font-size:12px;color:#888;margin-top:6px">sim-keyed CQ CQ CQ TST @ 20 wpm. Authentic path: send from AE's CWX &mdash; the sim follows AE's QSK.</div>
<script>
function sLabel(d){{var o=d+73;if(o>0)return '(S9+'+Math.round(o)+'dB)';return '(S'+Math.max(0,Math.round(9+o/6))+')';}}
var qskv=0;
var HINTS={{
carrier:"Steady carrier on the VFO. S-meter should read the signal level (dBm / S-unit); panadapter peak + solid waterfall stripe at centre.",
cw:"20-wpm Morse 'CQ CQ CQ TST'. Power meter keys the rhythm; waterfall flickers during keying — watch it recover cleanly after the over (#1916).",
noise_floor:"Flat, featureless noise floor (baseline). With AE auto-black on, the floor should sit even and dark (#3586).",
ramp:"Whole-span level swept min→max. Watch auto-black hold the floor even as level rises (#3586) and the colour map track it.",
cal_tones:"Tones at -100/-80/-60/-40 dBm. Verify the panadapter dB scale reads each one correctly (calibration card).",
swept_carrier:"Single tone sweeping the span. Check frequency mapping / waterfall tile decode (#3457).",
comb:"Evenly-spaced tones across the span. Dynamic range / many simultaneous bins.",
step:"Whole-span square wave in time. Temporal response / waterfall scroll timing.",
impulse:"Brief full-span flash each period. Transient response / paced fallback (#3182).",
tx_blank:"Periodic real TX gap (keys interlock + power). Watch the waterfall during and after TX — #2126 (flicker) / #1916 (disappears).",
staircase:"Centre carrier stepping floor→max in 10 even steps. Reads AE's colormap / black-threshold as a ladder.",
noise:"Random noise band, white→pink tilt. Floor texture and colour mapping."
}};
function setp(p){{pat.value=p;upd();}}
function sendcw(q){{qskv=q;pat.value='cw';upd();}}
function upd(){{var h=HINTS[pat.value];if(h)hint.textContent=h;
floorv.textContent=floor.value;levelv.textContent=level.value;
floors.textContent=sLabel(+floor.value);levels.textContent=sLabel(+level.value);
widthv.textContent=width.value;tiltv.textContent=tilt.value;
txpwv.textContent=txpw.value;var sv=(swr.value/10).toFixed(1);swrv.textContent=sv;
fetch('/set?pattern='+pat.value+'&floor='+floor.value+'&level='+level.value+'&width='+width.value+'&tilt='+tilt.value+'&tx='+(tx.checked?1:0)+'&txpw='+txpw.value+'&swr='+sv+'&qsk='+qskv);}}
upd();
</script></body></html>"""


def start_control_server(radio, port):
    opts = "".join(f'<option value="{p}"{" selected" if p == radio.pattern else ""}>{p}</option>'
                   for p in sorted(PATTERNS))
    page = CONTROL_HTML.format(options=opts).encode()

    class H(http.server.BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def do_GET(self):
            u = urllib.parse.urlparse(self.path)
            if u.path == "/set":
                q = urllib.parse.parse_qs(u.query)
                try:
                    if "floor" in q:   radio.noise_floor_dbm = float(q["floor"][0])
                    if "level" in q:   radio.sig_level_dbm = float(q["level"][0])
                    if "width" in q:   radio.sig_width_khz = float(q["width"][0])
                    if "tilt" in q:    radio.noise_color = float(q["tilt"][0])
                    if "txpw" in q:    radio.tx_power_w = float(q["txpw"][0])
                    if "swr" in q:     radio.tx_swr = float(q["swr"][0])
                    if "qsk" in q:     radio.qsk = q["qsk"][0] == "1"
                    if "tx" in q and radio.pattern not in AUTO_TX_PATTERNS and not radio.cwx_active:
                        newtx = q["tx"][0] == "1"
                        if newtx != radio.tx_mox:
                            radio.tx_mox = newtx
                            radio.emit_transmit_status()
                            log(f"[ctl] TX {'ON' if newtx else 'off'} "
                                f"({radio.tx_power_w:.0f} W, SWR {radio.tx_swr:.1f})")
                    if "pattern" in q and q["pattern"][0] in PATTERNS and q["pattern"][0] != radio.pattern:
                        leaving_auto = radio.pattern in AUTO_TX_PATTERNS
                        radio.pattern = q["pattern"][0]
                        if leaving_auto and radio.tx_mox:            # don't leave TX stuck on after a gap/over
                            radio.tx_mox = False
                            radio.emit_transmit_status()
                        log(f"[ctl] pattern -> {radio.pattern}  (floor={radio.noise_floor_dbm:.0f}dBm "
                            f"level={radio.sig_level_dbm:.0f}dBm width={radio.sig_width_khz:.0f} tilt={radio.noise_color:.0f})")
                except ValueError:
                    pass
                self.send_response(200); self.end_headers(); self.wfile.write(b"ok")
            else:
                self.send_response(200)
                self.send_header("Content-Type", "text/html")
                self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
                self.send_header("Pragma", "no-cache")
                self.end_headers(); self.wfile.write(page)

    srv = http.server.ThreadingHTTPServer(("0.0.0.0", port), H)
    threading.Thread(target=srv.serve_forever, daemon=True).start()


# ---- the rack: one process hosting N radios + a combined "1U strip" panel ----
class Rack:
    def __init__(self, ip, ae_ip, n, base_port, pattern, bins, fps, width_khz):
        self.radios = [Radio(ip, ae_ip, pattern, bins, fps, width_khz,
                             port=base_port + i, radio_id=i) for i in range(n)]

    def start(self):
        for r in self.radios:
            threading.Thread(target=r.discovery_loop, daemon=True).start()
            threading.Thread(target=r.prime_loop, daemon=True).start()
            threading.Thread(target=r.serve, daemon=True).start()


RACK_HTML = """<!DOCTYPE html><html><head><meta charset=utf-8><title>flex-sim rack</title>
<style>
body{{font-family:sans-serif;background:#0d0f13;color:#dfe7ef;margin:0;padding:18px}}
h2{{color:#5cf;margin:0 0 2px}} .sub{{color:#6b7480;font-size:13px;margin-bottom:14px}}
.rack{{background:#14171c;border:1px solid #2b313b;border-radius:12px;padding:10px;display:flex;flex-direction:column;gap:8px}}
.strip{{display:flex;align-items:center;gap:8px;background:#1b2129;border:1px solid #2f3742;border-radius:8px;padding:8px 6px}}
.strip.off{{background:#15181d;border-color:#23272e;opacity:.55}}
.pwr{{width:26px;height:26px;border-radius:50%;border:1px solid #2c7a44;background:#16331f;color:#34d058;cursor:pointer;font-size:13px;line-height:1}}
.pwr.off{{border-color:#3a3f47;background:#23272e;color:#5a616b}}
.rid{{width:74px;line-height:1.15}} .rid b{{font-size:13px}} .rid span{{display:block;font-size:10px;color:#6b7480}}
.lcd{{width:112px;font-family:monospace;font-size:14px;color:#f0b34a;background:#0c0e12;border-radius:4px;padding:4px 6px;text-align:right}}
.mode{{width:46px;font-size:11px;color:#9fb3c8;background:#232a33;border-radius:4px;padding:4px 0;text-align:center}}
.pill{{width:44px;font-size:11px;border-radius:4px;padding:4px 0;text-align:center;font-weight:bold}}
.pill.rx{{color:#4ade80;background:#123a1e;border:1px solid #1f6b35}}
.pill.tx{{color:#f87171;background:#3a1212;border:1px solid #6b1f1f}}
.pill.off{{color:#5a616b;background:#1e232a}}
select{{width:126px;font-size:12px;color:#cfe0f0;background:#232a33;border:1px solid #38414d;border-radius:5px;padding:4px 6px}}
.met{{flex:1;display:flex;align-items:center;gap:6px}}
.bar{{flex:1;height:10px;background:#0c0e12;border-radius:3px;overflow:hidden}}
.fill{{height:100%;width:0;background:#2faf5a}}
.mlbl{{font-size:11px;color:#9fb3c8;width:36px}}
</style></head><body>
<h2>flex-sim rack</h2><div class=sub>{n} virtual radios &mdash; driving AetherSDR</div>
<div class=rack>{strips}</div>
<script>
function fmtFreq(m){{var hz=Math.round(m*1e6),s=String(hz).padStart(7,'0');
return (s.slice(0,-6)||'0')+'.'+s.slice(-6,-3)+'.'+s.slice(-3);}}
function setp(i,p){{fetch('/set?radio='+i+'&pattern='+p);}}
function pwr(i,on){{fetch('/set?radio='+i+'&power='+(on?1:0));}}
function S(d){{return d>=-73?('S9+'+Math.round(d+73)):('S'+Math.max(0,Math.round(9+(d+73)/6)));}}
async function poll(){{
 try{{var st=await(await fetch('/state')).json();st.forEach(function(s){{
  var g=function(p){{return document.getElementById(p+'-'+s.id);}};
  g('strip').className='strip'+(s.on?'':' off');
  g('pwr').className='pwr'+(s.on?'':' off');
  g('lcd').textContent=s.on?fmtFreq(s.freq):'—.———.———';
  g('mode').textContent=s.on?s.mode:'—';
  var pl=g('state');
  if(!s.on){{pl.textContent='off';pl.className='pill off';}}
  else if(s.tx){{pl.textContent='TX';pl.className='pill tx';}}
  else{{pl.textContent='RX';pl.className='pill rx';}}
  var f=g('fill'),l=g('mlbl');
  if(!s.on){{f.style.width='0';l.textContent='—';}}
  else if(s.tx){{f.style.width=Math.min(100,s.power_w)+'%';f.style.background='#e0892a';l.textContent=s.power_w+'W';}}
  else{{f.style.width=Math.max(0,Math.min(100,(s.meter_dbm+130)/1.1))+'%';f.style.background='#2faf5a';l.textContent=S(s.meter_dbm);}}
 }});}}catch(e){{}}
 setTimeout(poll,750);
}}
poll();
</script></body></html>"""


def start_rack_control_server(rack, port):
    def strip(r):
        opts = "".join(f'<option{" selected" if p == r.pattern else ""}>{p}</option>'
                       for p in sorted(PATTERNS))
        i = r.radio_id
        return (f'<div class=strip id=strip-{i}>'
                f'<button class=pwr id=pwr-{i} title=power '
                f'onclick="pwr({i},this.classList.contains(\'off\'))">&#9211;</button>'
                f'<span class=rid><b>R{i + 1}</b><span>{r.serial}</span></span>'
                f'<span class=lcd id=lcd-{i}>&mdash;.&mdash;&mdash;&mdash;.&mdash;&mdash;&mdash;</span>'
                f'<span class=mode id=mode-{i}>&mdash;</span>'
                f'<span class="pill off" id=state-{i}>off</span>'
                f'<select id=pat-{i} onchange="setp({i},this.value)">{opts}</select>'
                f'<span class=met><span class=bar><span class=fill id=fill-{i}></span></span>'
                f'<span class=mlbl id=mlbl-{i}>&mdash;</span></span></div>')
    page = RACK_HTML.format(n=len(rack.radios), strips="".join(strip(r) for r in rack.radios)).encode()

    class H(http.server.BaseHTTPRequestHandler):
        def log_message(self, *a): pass

        def do_GET(self):
            u = urllib.parse.urlparse(self.path)
            if u.path == "/state":
                body = json.dumps([r.state() for r in rack.radios]).encode()
                self.send_response(200); self.send_header("Content-Type", "application/json")
                self.send_header("Cache-Control", "no-store"); self.end_headers()
                self.wfile.write(body); return
            if u.path == "/set":
                q = urllib.parse.parse_qs(u.query)
                try:
                    r = rack.radios[int(q.get("radio", ["0"])[0])]
                    if "power" in q:
                        r.set_power(q["power"][0] == "1")
                        log(f"[rack] R{r.radio_id + 1} power {'on' if r.enabled else 'off'}")
                    if "pattern" in q and q["pattern"][0] in PATTERNS and q["pattern"][0] != r.pattern:
                        leaving_auto = r.pattern in AUTO_TX_PATTERNS
                        r.pattern = q["pattern"][0]
                        if leaving_auto and r.tx_mox:
                            r.tx_mox = False; r.emit_transmit_status()
                        log(f"[rack] R{r.radio_id + 1} pattern -> {r.pattern}")
                except (ValueError, IndexError):
                    pass
                self.send_response(200); self.end_headers(); self.wfile.write(b"ok"); return
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
            self.send_header("Pragma", "no-cache")
            self.end_headers(); self.wfile.write(page)

    srv = http.server.ThreadingHTTPServer(("0.0.0.0", port), H)
    threading.Thread(target=srv.serve_forever, daemon=True).start()


def main():
    ap = argparse.ArgumentParser(prog="flex-sim",
                                 description="Synthetic FlexRadio-6000 emulator / test bench for AetherSDR.")
    ap.add_argument("--version", action="version", version=f"flex-sim {FLEX_SIM_VERSION}")
    ap.add_argument("--ip", default=None)
    ap.add_argument("--ae", default=None)
    ap.add_argument("--pattern", default="ramp", choices=sorted(PATTERNS))
    ap.add_argument("--bins", type=int, default=BINS)
    ap.add_argument("--fps", type=int, default=FPS)
    ap.add_argument("--width-khz", type=float, default=SIGNAL_WIDTH_KHZ)
    ap.add_argument("--port", type=int, default=DEFAULT_PORT,
                    help="control/data port we bind + advertise (default 4992; set e.g. 5992 to "
                         "coexist with AE on one host). Discovery is always sent to AE's :4992.")
    ap.add_argument("--radios", type=int, default=1,
                    help="number of virtual radios in one process (>1 = rack mode)")
    ap.add_argument("--base-port", type=int, default=None,
                    help="rack: first radio's port; radios use base..base+N-1 (default = --port)")
    ap.add_argument("--ctl-port", type=int, default=8731, help="web control-panel port")
    args = ap.parse_args()
    ip = args.ip or local_ip()
    if args.radios > 1:                                    # ---- rack mode: N radios + strip panel ----
        base = args.base_port or args.port
        rack = Rack(ip, args.ae, args.radios, base, args.pattern, args.bins, args.fps, args.width_khz)
        rack.start()
        start_rack_control_server(rack, args.ctl_port)
        log(f"flex-sim {FLEX_SIM_VERSION} - RACK of {args.radios} radios "
            f"(FLEXSIM00..FLEXSIM{args.radios - 1:02d}, ports {base}..{base + args.radios - 1}) ip {ip}")
        log(f"discovery -> AE's UDP :{DISCOVERY_PORT}")
        log(f"** rack panel: http://{ip}:{args.ctl_port}/  (open in your host browser) **")
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            log("bye")
        return
    radio = Radio(ip, args.ae, args.pattern, args.bins, args.fps, args.width_khz, port=args.port)
    threading.Thread(target=radio.discovery_loop, daemon=True).start()
    threading.Thread(target=radio.prime_loop, daemon=True).start()
    start_control_server(radio, args.ctl_port)
    log(f"flex-sim {FLEX_SIM_VERSION} - model={MODEL} serial={radio.serial} ip={ip} pattern={args.pattern}")
    log(f"discovery -> AE's UDP :{DISCOVERY_PORT}; control/data on :{args.port}"
        + ("  (same-host mode)" if args.port != DISCOVERY_PORT else ""))
    log(f"** control panel: http://{ip}:{args.ctl_port}/  (open in your host browser) **")
    try:
        radio.serve()
    except KeyboardInterrupt:
        radio.run = False
        log("bye")


if __name__ == "__main__":
    main()
